force-app/main/default/objects/INV_CO_Reminder__c/INV_CO_Reminder__c.object-meta.xml
<CustomObject>
    <label>Reminder</label>
    <nameField>
        <label>Reminder Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reminders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INV_CO_Reminder__c/fields/INV_CompletionStatus__c.field-meta.xml
<CustomField>
    <fullName>INV_CompletionStatus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Completion Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/INV_CO_Reminder__c/fields/INV_Priority__c.field-meta.xml
<CustomField>
    <fullName>INV_Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INV_CO_Reminder__c/fields/INV_ReminderDateTime__c.field-meta.xml
<CustomField>
    <fullName>INV_ReminderDateTime__c</fullName>
    <label>Reminder Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/INV_AX001_PopupReminderController.cls
public with sharing class INV_AX001_PopupReminderController {
    @AuraEnabled(cacheable=true)
    public static List<INV_CO_Reminder__c> getMyReminders() {
        return [
            SELECT Id, Name, INV_Priority__c, INV_ReminderDateTime__c
            FROM INV_CO_Reminder__c
            WHERE OwnerId = :UserInfo.getUserId() 
            AND INV_CompletionStatus__c = false
            AND INV_ReminderDateTime__c >= :DateTime.now()
            AND INV_ReminderDateTime__c <= :DateTime.now().addMinutes(30)
            ORDER BY INV_ReminderDateTime__c ASC
        ];
    }

    @AuraEnabled
    public static void markReminderAsCompleted(Id reminderId) {
        INV_CO_Reminder__c reminder = [SELECT Id, INV_CompletionStatus__c FROM INV_CO_Reminder__c WHERE Id = :reminderId LIMIT 1];
        if(reminder != null) {
            reminder.INV_CompletionStatus__c = true;
            update reminder;
        }
    }
}